name: Ubuntu Bionic CI

on: [push]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: chapulina/ubuntu-bionic-ci-action@master
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
