name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  triage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: chapulina/labeler@schedule
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
