name: Periodic triage
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Add collection labels
        uses: ignition-tooling/pr-collection-labeler@chapulina/periodic
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: '$GITHUB_REPOSITORY'
          gazebodistro-branch: 'chapulina/testing'
